import { ControlType, decodeFskSamples, decodeQuadFskHandshakeSamples, decodeQuadFskSamples, encodeCompactFskPacket, encodeFskPacket, encodeQuadCompactFskPacket, encodeQuadFskHandshakePacket, encodeQuadFskPacket, makeBlockStatusPayload, makeCompactStatusPayload, packCompactControlPacket, readBlockStatusPayload, readCompactStatusPayload } from './control.ts'
import { OCTAL_FAST_SYMBOL_SECONDS, decodeOctalFskSamples, encodeOctalCompactFskPacket, encodeOctalFskHandshakePacket, encodeOctalFskPacket } from './octal-fsk.ts'
import { OPTICAL_OFFER_HOLD_MS, makeOpticalQualityPayload, nextOpticalOfferHold, readOpticalQualityPayload } from './optical-feedback.ts'

const payload = makeBlockStatusPayload(96, 0xf0a20cc3)
const packet = { type: ControlType.BLOCK_STATUS, transferId: 0x9127ea45, sequence: 44, payload }
const encoded = encodeFskPacket(packet, 48000)
const samples = new Float32Array(encoded.length + 2117)
for (let index = 0; index < samples.length; index += 1) samples[index] = (((index * 17) % 31) - 15) * 0.0006
samples.set(encoded, 2117)
const decoded = decodeFskSamples(samples, 48000)
if (decoded.length !== 1 || decoded[0].transferId !== packet.transferId || decoded[0].sequence !== packet.sequence) throw new Error('Acoustic packet failed synthetic round trip')
const status = readBlockStatusPayload(decoded[0].payload)
if (!status || status.baseBlock !== 96 || status.bitmap !== 0xf0a20cc3) throw new Error('Acoustic block bitmap changed')
const sessionId = 0x6135d902
const manifestTag = Uint8Array.from({ length: 12 }, (_, index) => index * 13)
const manifestTone = encodeOctalFskPacket({ type: ControlType.MANIFEST_READY, transferId: sessionId, sequence: 19, payload: manifestTag }, 48000)
const manifestPacket = decodeOctalFskSamples(manifestTone, 48000)
if (manifestPacket.length !== 1 || manifestPacket[0].type !== ControlType.MANIFEST_READY || manifestPacket[0].sequence !== 19 || manifestPacket[0].payload.some((value, index) => value !== manifestTag[index])) throw new Error('Authenticated manifest-ready control did not survive 8-FSK')
const brokenManifestTone = manifestTone.slice(); brokenManifestTone.fill(0, Math.floor(brokenManifestTone.length / 3), Math.floor(brokenManifestTone.length * 2 / 3))
if (decodeOctalFskSamples(brokenManifestTone, 48000).length) throw new Error('Corrupted manifest-ready control passed acoustic CRC')
const hello = decodeFskSamples(encodeFskPacket({ type: ControlType.HELLO, transferId: sessionId, sequence: 1, payload: new Uint8Array() }, 48000), 48000)
if (hello.length !== 1 || hello[0].type !== ControlType.HELLO || hello[0].transferId !== sessionId || hello[0].payload.length) throw new Error('Acoustic session HELLO failed')
const storageHello = decodeFskSamples(encodeFskPacket({ type: ControlType.HELLO, transferId: sessionId, sequence: 3, payload: Uint8Array.of(0) }, 48000), 48000)
if (storageHello.length !== 1 || storageHello[0].payload.length !== 1 || storageHello[0].payload[0] !== 0) throw new Error('Receiver storage capability changed during acoustic HELLO')
const ready = decodeFskSamples(encodeFskPacket({ type: ControlType.READY, transferId: sessionId, sequence: 2, payload }, 48000), 48000)
const readyStatus = ready.length === 1 ? readBlockStatusPayload(ready[0].payload) : null
if (ready.length !== 1 || ready[0].type !== ControlType.READY || ready[0].transferId !== sessionId || readyStatus?.bitmap !== 0xf0a20cc3) throw new Error('Acoustic READY and first ACK failed')
const compactPayload = makeCompactStatusPayload(12345, 0b1010, 4)
const compactPacket = { type: ControlType.BLOCK_STATUS, transferId: sessionId, sequence: 9, payload: compactPayload }
const compactSound = encodeCompactFskPacket(compactPacket, 48000)
const compactDecoded = decodeFskSamples(compactSound, 48000)
const compactStatus = compactDecoded.length === 1 ? readCompactStatusPayload(compactDecoded[0].payload) : null
if (compactDecoded.length !== 1 || compactDecoded[0].transferId !== sessionId || compactDecoded[0].sequence !== 9 || compactStatus?.firstMissing !== 12345 || compactStatus.bitmap !== 0b1010 || compactStatus.paceCode !== 4) throw new Error('Compact cumulative block ACK and pace report failed')
const selected = decodeFskSamples(encodeCompactFskPacket({ type: ControlType.CALIBRATION_SELECTED, transferId: sessionId, sequence: 10, payload: Uint8Array.of(1, 1, 4, 0) }, 48000), 48000)
if (selected.length !== 1 || selected[0].type !== ControlType.CALIBRATION_SELECTED || selected[0].payload[2] !== 4) throw new Error('Acoustic calibration selection failed')
if (compactSound.length >= encoded.length * 0.65) throw new Error('Compact ACK did not materially shorten the audio packet')
const mixedHello = encodeFskPacket({ type: ControlType.HELLO, transferId: sessionId, sequence: 8, payload: new Uint8Array() }, 48000)
const mixed = new Float32Array(mixedHello.length + 1000 + compactSound.length)
mixed.set(mixedHello); mixed.set(compactSound, mixedHello.length + 1000)
const mixedDecoded = decodeFskSamples(mixed, 48000)
if (mixedDecoded.length !== 2 || mixedDecoded[0].type !== ControlType.HELLO || mixedDecoded[1].type !== ControlType.BLOCK_STATUS) throw new Error('Mixed handshake and compact ACK were not decoded in sound order')
const compactCorrupted = compactSound.slice()
compactCorrupted.fill(0, Math.floor(compactCorrupted.length / 3), Math.floor(compactCorrupted.length * 2 / 3))
if (decodeFskSamples(compactCorrupted, 48000).length) throw new Error('Corrupted compact ACK passed CRC')
const linkPayload = Uint8Array.of(2, 1) // optical profile 2, protocol version 1
for (const [index, type] of [ControlType.PROFILE_SELECTED, ControlType.PAUSE, ControlType.RESUME].entries()) {
  const link = decodeFskSamples(encodeFskPacket({ type, transferId: sessionId, sequence: 5 + index, payload: linkPayload }, 48000), 48000)
  if (link.length !== 1 || link[0].type !== type || link[0].transferId !== sessionId || link[0].payload[0] !== 2 || link[0].payload[1] !== 1) throw new Error('Acoustic optical-link control failed')
}
const corrupted = samples.slice()
corrupted.fill(0, Math.floor(corrupted.length / 2), Math.floor(corrupted.length / 2) + 48000)
if (decodeFskSamples(corrupted, 48000).length) throw new Error('Corrupted acoustic control passed CRC')
const fragment = { type: ControlType.HANDSHAKE_FRAGMENT, transferId: sessionId, sequence: 77, payload: Uint8Array.from({ length: 12 }, (_, index) => index * 17 & 255) }
const quadSound = encodeQuadFskHandshakePacket(fragment, 48000)
const shiftedQuad = new Float32Array(quadSound.length + 2301)
shiftedQuad.set(quadSound, 2301)
for (let index = 0; index < shiftedQuad.length; index += 1) shiftedQuad[index] += (((index * 17) % 31) - 15) * 0.0006
const quadDecoded = decodeQuadFskHandshakeSamples(shiftedQuad, 48000)
if (quadDecoded.length !== 1 || quadDecoded[0].transferId !== sessionId || quadDecoded[0].sequence !== 77 || quadDecoded[0].payload.some((value, index) => value !== fragment.payload[index])) throw new Error('Four-tone handshake packet failed noisy, offset round trip')
const withoutSync = quadSound.slice(); withoutSync.fill(0, 0, Math.round(48000 * 0.04))
if (decodeQuadFskHandshakeSamples(withoutSync, 48000).length) throw new Error('Four-tone packet was accepted without its unique sync tone')
const corruptedQuad = quadSound.slice(); corruptedQuad.fill(0, Math.floor(corruptedQuad.length * 0.55), Math.floor(corruptedQuad.length * 0.75))
if (decodeQuadFskHandshakeSamples(corruptedQuad, 48000).length) throw new Error('Corrupted four-tone packet passed CRC')
const quad44100 = decodeQuadFskHandshakeSamples(encodeQuadFskHandshakePacket(fragment, 44100), 44100)
if (quad44100.length !== 1 || quad44100[0].sequence !== 77) throw new Error('Four-tone packet failed at 44.1 kHz')
const nextFragmentSound = encodeQuadFskHandshakePacket({ ...fragment, sequence: 78 }, 48000)
const adjacentQuad = new Float32Array(quadSound.length + 720 + nextFragmentSound.length)
adjacentQuad.set(quadSound); adjacentQuad.set(nextFragmentSound, quadSound.length + 720)
const adjacentDecoded = decodeQuadFskHandshakeSamples(adjacentQuad, 48000)
if (adjacentDecoded.length !== 2 || adjacentDecoded[0].sequence !== 77 || adjacentDecoded[1].sequence !== 78) throw new Error('Four-tone packet-start marker failed on adjacent fragments')
if (quadSound.length >= encodeFskPacket(fragment, 48000).length * 0.6) throw new Error('Four-tone handshake did not shorten the acoustic waveform')
let rejectedRuntimeQuad = false
try { encodeQuadFskHandshakePacket(compactPacket, 48000) } catch { rejectedRuntimeQuad = true }
if (!rejectedRuntimeQuad) throw new Error('Four-tone handshake codec accepted a runtime ACK')
const quadCompactSound = encodeQuadCompactFskPacket(compactPacket, 48000)
const quadCompactDecoded = decodeQuadFskSamples(quadCompactSound, 48000)
const quadCompactStatus = quadCompactDecoded.length === 1 ? readCompactStatusPayload(quadCompactDecoded[0].payload) : null
if (packCompactControlPacket(compactPacket).length !== 14 || quadCompactDecoded.length !== 1 || quadCompactDecoded[0].sequence !== compactPacket.sequence || quadCompactStatus?.firstMissing !== 12345 || quadCompactStatus.bitmap !== 0b1010 || quadCompactStatus.paceCode !== 4) throw new Error('Four-tone compact ACK changed the 14-byte body or decoded incorrectly')
if (decodeFskSamples(quadCompactSound, 48000).length) throw new Error('Legacy binary decoder accepted a four-tone ACK')
const emptyRuntime = { type: ControlType.TRANSFER_COMPLETE, transferId: sessionId, sequence: 15, payload: new Uint8Array() }
const quadEmptyRuntime = decodeQuadFskSamples(encodeQuadFskPacket(emptyRuntime, 48000), 48000)
if (quadEmptyRuntime.length !== 1 || quadEmptyRuntime[0].type !== ControlType.TRANSFER_COMPLETE) throw new Error('Four-tone normal packet with empty payload failed')
const quadPause = { type: ControlType.PAUSE, transferId: sessionId, sequence: 16, payload: linkPayload }
const quadPauseDecoded = decodeQuadFskSamples(encodeQuadFskPacket(quadPause, 48000), 48000)
if (quadPauseDecoded.length !== 1 || quadPauseDecoded[0].type !== ControlType.PAUSE || quadPauseDecoded[0].payload[1] !== 1) throw new Error('Four-tone runtime link packet failed')
const adjacentRuntime = new Float32Array(quadCompactSound.length + 720 + encodeQuadFskPacket(quadPause, 48000).length)
adjacentRuntime.set(quadCompactSound); adjacentRuntime.set(encodeQuadFskPacket(quadPause, 48000), quadCompactSound.length + 720)
const adjacentRuntimeDecoded = decodeQuadFskSamples(adjacentRuntime, 48000)
if (adjacentRuntimeDecoded.length !== 2 || adjacentRuntimeDecoded[0].type !== ControlType.BLOCK_STATUS || adjacentRuntimeDecoded[1].type !== ControlType.PAUSE) throw new Error('Adjacent mixed compact and normal four-tone control failed')
const corruptedQuadAck = quadCompactSound.slice(); corruptedQuadAck.fill(0, Math.floor(corruptedQuadAck.length * 0.55), Math.floor(corruptedQuadAck.length * 0.75))
if (decodeQuadFskSamples(corruptedQuadAck, 48000).length) throw new Error('Corrupted four-tone compact ACK passed CRC')
if (quadCompactSound.length / 48000 !== 1.2 || quadCompactSound.length >= compactSound.length * 0.6) throw new Error('Four-tone compact ACK duration regressed')
const octalSound = encodeOctalFskHandshakePacket(fragment, 48000)
const shiftedOctal = new Float32Array(octalSound.length + 2301)
shiftedOctal.set(octalSound, 2301)
for (let index = 0; index < shiftedOctal.length; index += 1) shiftedOctal[index] += (((index * 17) % 31) - 15) * 0.0006
const octalDecoded = decodeOctalFskSamples(shiftedOctal, 48000)
if (octalDecoded.length !== 1 || octalDecoded[0].sequence !== fragment.sequence || octalDecoded[0].payload.some((value, index) => value !== fragment.payload[index])) throw new Error('Eight-tone handshake packet failed noisy, offset round trip')
const octal44100 = decodeOctalFskSamples(encodeOctalFskHandshakePacket(fragment, 44100), 44100)
if (octal44100.length !== 1 || octal44100[0].sequence !== fragment.sequence) throw new Error('Eight-tone packet failed at 44.1 kHz')
for (const sampleRate of [44100, 48000]) {
  const fastSound = encodeOctalFskHandshakePacket(fragment, sampleRate, OCTAL_FAST_SYMBOL_SECONDS)
  const shiftedFast = new Float32Array(fastSound.length + Math.round(sampleRate * 0.037))
  shiftedFast.set(fastSound, shiftedFast.length - fastSound.length)
  for (let index = 0; index < shiftedFast.length; index += 1) shiftedFast[index] += (((index * 17) % 31) - 15) * 0.0006
  const decoded = decodeOctalFskSamples(shiftedFast, sampleRate, OCTAL_FAST_SYMBOL_SECONDS)
  if (decoded.length !== 1 || decoded[0].sequence !== fragment.sequence || decoded[0].payload.some((value, index) => value !== fragment.payload[index])) throw new Error('Fast eight-tone handshake failed noisy, offset round trip')
  if (decodeOctalFskSamples(fastSound, sampleRate).length) throw new Error('Fast eight-tone packet was accepted at legacy symbol rate')
}
const octalCompactSound = encodeOctalCompactFskPacket(compactPacket, 48000)
const octalCompactDecoded = decodeOctalFskSamples(octalCompactSound, 48000)
const octalCompactStatus = octalCompactDecoded.length === 1 ? readCompactStatusPayload(octalCompactDecoded[0].payload) : null
if (octalCompactDecoded.length !== 1 || octalCompactDecoded[0].sequence !== compactPacket.sequence || octalCompactStatus?.firstMissing !== 12345 || octalCompactStatus.bitmap !== 0b1010 || octalCompactStatus.paceCode !== 4) throw new Error('Eight-tone compact ACK failed')
const fastCompactSound = encodeOctalCompactFskPacket(compactPacket, 48000, OCTAL_FAST_SYMBOL_SECONDS)
const fastCompactDecoded = decodeOctalFskSamples(fastCompactSound, 48000, OCTAL_FAST_SYMBOL_SECONDS)
if (fastCompactDecoded.length !== 1 || fastCompactDecoded[0].sequence !== compactPacket.sequence || readCompactStatusPayload(fastCompactDecoded[0].payload)?.firstMissing !== 12345) throw new Error('Fast eight-tone compact ACK failed')
if (fastCompactSound.length >= octalCompactSound.length * 0.8) throw new Error('Fast eight-tone compact ACK did not shorten airtime')
const octalPause = decodeOctalFskSamples(encodeOctalFskPacket(quadPause, 48000), 48000)
if (octalPause.length !== 1 || octalPause[0].type !== ControlType.PAUSE) throw new Error('Eight-tone normal runtime control failed')
const qualityPacket = { type: ControlType.OPTICAL_QUALITY, transferId: sessionId, sequence: 91, payload: makeOpticalQualityPayload(6, 2) }
const qualitySound = encodeOctalFskPacket(qualityPacket, 48000)
const qualityDecoded = decodeOctalFskSamples(qualitySound, 48000)
if (qualityDecoded.length !== 1 || qualityDecoded[0].type !== ControlType.OPTICAL_QUALITY || qualityDecoded[0].transferId !== sessionId || readOpticalQualityPayload(qualityDecoded[0].payload)?.holdCode !== 2 || OPTICAL_OFFER_HOLD_MS[2] !== 1500) throw new Error('RGB quality feedback failed eight-tone round trip')
if (nextOpticalOfferHold(400, sessionId, 6, qualityDecoded[0]) !== 1500 || nextOpticalOfferHold(1500, sessionId, 6, qualityDecoded[0]) !== 1500 || nextOpticalOfferHold(400, sessionId + 1, 6, qualityDecoded[0]) !== 400 || nextOpticalOfferHold(400, sessionId, 5, qualityDecoded[0]) !== 400) throw new Error('RGB quality hint was not session/profile bound or allowed a faster offer')
const damagedQuality = qualitySound.slice(); damagedQuality.fill(0, Math.floor(damagedQuality.length * 0.55), Math.floor(damagedQuality.length * 0.75))
if (decodeOctalFskSamples(damagedQuality, 48000).length) throw new Error('Corrupted RGB quality feedback passed CRC')
if (readOpticalQualityPayload(Uint8Array.of(1, 6, 1, 3)) || readOpticalQualityPayload(Uint8Array.of(1, 6, 2, 1))) throw new Error('Malformed RGB quality feedback accepted')
const adjacentOctal = new Float32Array(octalCompactSound.length + 720 + octalSound.length)
adjacentOctal.set(octalCompactSound); adjacentOctal.set(octalSound, octalCompactSound.length + 720)
const adjacentOctalDecoded = decodeOctalFskSamples(adjacentOctal, 48000)
if (adjacentOctalDecoded.length !== 2 || adjacentOctalDecoded[0].type !== ControlType.BLOCK_STATUS || adjacentOctalDecoded[1].type !== ControlType.HANDSHAKE_FRAGMENT) throw new Error('Adjacent eight-tone compact and normal packets failed')
if (decodeQuadFskSamples(octalSound, 48000).length || decodeFskSamples(octalSound, 48000).length) throw new Error('Older modem accepted an eight-tone packet')
const octalWithoutSync = octalSound.slice(); octalWithoutSync.fill(0, 0, Math.round(48000 * 0.04))
if (decodeOctalFskSamples(octalWithoutSync, 48000).length) throw new Error('Eight-tone packet accepted without marker')
const octalCorrupted = octalCompactSound.slice(); octalCorrupted.fill(0, Math.floor(octalCorrupted.length * 0.55), Math.floor(octalCorrupted.length * 0.75))
if (decodeOctalFskSamples(octalCorrupted, 48000).length) throw new Error('Corrupted eight-tone ACK passed CRC')
if (octalCompactSound.length / 48000 !== 0.784 || octalCompactSound.length >= quadCompactSound.length * 0.7) throw new Error('Eight-tone compact ACK duration regressed')
console.log(JSON.stringify({ result: 'ok', bitsPerSecond: Math.round(1 / 0.016), packetSeconds: Number((encoded.length / 48000).toFixed(2)), compactAckSeconds: Number((compactSound.length / 48000).toFixed(2)), quadCompactAckSeconds: Number((quadCompactSound.length / 48000).toFixed(2)), octalCompactAckSeconds: Number((octalCompactSound.length / 48000).toFixed(3)), fastOctalCompactAckSeconds: Number((fastCompactSound.length / 48000).toFixed(3)) }))
